server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 如果返回字段是null也要返回
    call-setters-on-nulls: true
  mapper-locations: /mapper/*
wxAppId: wx4360135e5a95b229
wxAppSecret: 8f6a71d12bf8e3652de2427d472ad1dc
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345!
    url: jdbc:mysql://localhost:3306/whisper?useUnicode=true&characterEncoding=utf-8&useSSL=false
    hikari:
      connection-init-sql: SELECT 1
